spring.application.name=backend-LevelUP
server.port=8080
server.servlet.context-path=/api/v1

# --- NUEVA CONEXIÓN AWS RDS ---
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=REDACTED_DB_PASSWORD
spring.datasource.driver-class-name=org.postgresql.Driver

# --- Configuración JPA ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# --- Seguridad JWT ---
security.jwt.secret-key=REDACTED_JWT_SECRET
security.jwt.expiration-time=86400000